from datetime import datetime, timezone


# ==========================================================
# QUESTION DOCUMENT
# ==========================================================

def question_document(
    question: dict
) -> dict:

    now = datetime.now(
        timezone.utc
    )

    document = {

        # --------------------------------------------------
        # RELATIONSHIPS
        # --------------------------------------------------

        "assessment_id":
            question["assessment_id"],

        "section_id":
            question["section_id"],

        # --------------------------------------------------
        # QUESTION
        # --------------------------------------------------

        "question_type":
            question["question_type"],

        "question_text":
            question["question_text"],

        # --------------------------------------------------
        # MARKING
        # --------------------------------------------------

        "marks":
            question["marks"],

        "negative_marks":
            question["negative_marks"],

        # --------------------------------------------------
        # MCQ
        # --------------------------------------------------

        "options":
            question.get(
                "options"
            ),

        "expected_answer":
            question.get(
                "expected_answer"
            ),

        # --------------------------------------------------
        # MODEL ANSWER TEXT
        # --------------------------------------------------

        "model_answer_text":
            question.get(
                "model_answer_text"
            ),

        # --------------------------------------------------
        # MODEL ANSWER PDF
        #
        # This is generated by the backend after the teacher
        # uploads the PDF.
        # --------------------------------------------------

        "model_answer_pdf_url":
            question.get(
                "model_answer_pdf_url"
            ),

        # --------------------------------------------------
        # ORDER
        # --------------------------------------------------

        "order":
            question["order"],

        # --------------------------------------------------
        # TIMESTAMPS
        # --------------------------------------------------

        "created_at":
            now,

        "updated_at":
            now
    }

    return document